import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '@/components/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Bhagvat Gita
          </p>
        </div>

        <div className={styles.center}>
          {/* <Image
            // className={styles.logo}
            src="/gita.jpg"
            alt="Next.js Logo"
            width={200}
            height={130}
            priority
          /> */}
          {/* <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div> */}
        </div>

        <div className={styles.grid}>
          {data.map(item => <Card data={item} />)}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://bhagavadgitaapi.in/chapters`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}